### ISSUE TITLE
Pavel: create main text

### ISSUE THREAD

**Issue by gelilaa** [gelilaa/Integrate-3#3]
3. main text

> assigned to Pavel

__As a site visitor, I want to learn about something cool__

### Repository

- [ ] developed on a branch called `introduction`

### HTML

- [ ] An article element ...
- [ ] ... with the page's main content
- [ ] ... and class "main-text"

### CSS

- [ ] the "main-text" class

---

**Comment by aame1** [comment]
@pavelbidenko2018 : all you need to do (if you want) is tick the list items to mark that you've completed all your tasks :).
